image: leonschoorl/clash-ci-image:trusty

before_script:
  - export PATH="/opt/ghc/bin:/opt/cabal/bin:$PATH"

ghc-8.4.3:
  script:
    - pwd
    - export
    - apt-get update -q && apt-get install -yq cabal-install-head ghc-8.4.3
    - ghc --version
    - cabal --version
    - .ci/build.sh
    - .ci/test.sh
