image: leonschoorl/clash-ci-image:trusty

ghc-8.4.4:
  cache:
    key: cabal-store-8.4.4
    paths:
      - .cabal/store/
  script:
    - pwd
    - echo $HOME
    - export HOME=$(pwd)
    - export
    - cat /proc/cpuinfo
    - lscpu
    - dirname ~/.cabal
    - ls -la --color ~
    - apt-get update -q && apt-get install -yq cabal-install-head ghc-8.4.4
    - ghc --version
    - cabal --version
    - |
      echo -e 'package clash-testsuite\n  flags: travisci\npackage *\n  documentation: False' >> cabal.project.local && cat cabal.project.local
    - .ci/build.sh
    - ls -l ~/.cabal
    - .ci/test.sh

ghc-8.2.2:
  cache:
    key: cabal-store-8.2.2
    paths:
      - .cabal/store/
  script:
    - pwd
    - echo $HOME
    - export HOME=$(pwd)
    - export
    - apt-get update -q && apt-get install -yq cabal-install-head ghc-8.2.2
    - ghc --version
    - cabal --version
    - |
      echo -e 'package clash-testsuite\n  flags: travisci\npackage *\n  documentation: False' >> cabal.project.local && cat cabal.project.local
    - .ci/build.sh
    - .ci/test.sh
