version: 2
jobs:
  build-8.2.2:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: haskell:8.2.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ghc --version
      - run: cabal --version
  build-8.4.3:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: haskell:8.4.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ghc --version
      - run: cabal --version

workflows:
  version: 2
  build_multiple_ghc_version:
    jobs:
      - build-8.2.2
      - build-8.4.3
