version: 2
jobs:
  build-8.2.2:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - run: ghc --version
      - run: cabal --version
      - run: cabal new-update
      - run: cabal new-build all
      - run: cabal new-test all
      - run: cabal new-run -- clash-testsuite -j16
  build-8.4.3:
    docker:
      - image: haskell:8.4.3
    steps:
      - checkout
      - run: ghc --version
      - run: cabal --version
      - run: cabal new-update
      - run: cabal new-build all
      - run: cabal new-test all
      - run: cabal new-run -- clash-testsuite -j16

workflows:
  version: 2
  build_multiple_ghc_version:
    jobs:
      - build-8.2.2
      - build-8.4.3
