version: 2

workflows:
  version: 2
  build_multiple_ghc_version:
    jobs:
      # - build-8.2.2
      - build-8.4.3

aliases:
  - &env
    DEBIAN_FRONTEND: noninteractive
    CABAL_VERSION: head
  - &submodules
    run:
      name: "Checkout submodules"
      command: git submodule update --init --depth 1
  - &install_ghc
    run:
      name: Install ghc and cabal-install
      command: apt-get update -q && apt-get install -yq cabal-install-$CABAL_VERSION ghc-$GHC_VERSION
  - &update_path
    run:
      name: Update PATH
      command: |
        echo 'export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH' >> $BASH_ENV
        source $BASH_ENV
  - &cache_restore
    restore_cache:
      keys:
        - cabal-store-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "cabal.project" }}
        - cabal-store-{{ .Environment.CIRCLE_JOB }}-
  - &cache_save
    save_cache:
      key: cabal-store-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "cabal.project" }}
      paths:
        - /root/.cabal/store


jobs:
  build-8.4.3:
    environment:
      <<: *env
      GHC_VERSION: 8.4.3
    docker:
      - image: leonschoorl/clash-ci-image:trusty
    steps:
      - checkout
      - *submodules
      - *install_ghc
      - *update_path
      - run:
          name: Disable testing with Modelsim (SystemVerilog)
          command: |
            echo -e 'package clash-testsuite\n  flags: travisci' >> cabal.project && cat cabal.project
      - run:
          name: Show GHC and cabal versions
          command: ghc --version && cabal --version
      - *cache_restore
      - run: cabal new-update
      - run: cabal new-build all
      - run: cabal new-test all
      - *cache_save
      - run:
          name: Run clash-testsuite
          command: cabal new-run -- clash-testsuite -j16
