version: 2
jobs:
  build-8.4.3:
    docker:
      - image: leonschoorl/clash-ci-image:trusty
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: "Checkout submodules"
          command: git submodule update --init
      - run:
          name: Disable testing with Modelsim (SystemVerilog)
          command: |
            echo -e 'package clash-testsuite\n  flags: travisci' >> cabal.project && cat cabal.project
      - run: apt-get update -q && apt-get install -yq cabal-install-head ghc-8.4.3
      - run:
          name: Update PATH at Runtime
          command: |
            echo 'export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Show GHC and cabal versions
          command: ghc --version && cabal --version
      - restore_cache:
          keys:
            - cabal-store-8.4.3-{{ checksum ".circleci/config.yml "}}
            - cabal-store-8.4.3-
      - run: cabal new-update
      - run: cabal new-build all
      - save_cache:
          key: cabal-store-8.4.3-{{ checksum ".circleci/config.yml "}}
          paths:
            - /root/.cabal/store
      - run: cabal new-test all
      - run: cabal new-run -- clash-testsuite -j16

workflows:
  version: 2
  build_multiple_ghc_version:
    jobs:
      # - build-8.2.2
      - build-8.4.3
