version: 2
jobs:
  build-8.4.3:
    docker:
      - image: leonschoorl/clash-ci-image:trusty
    steps:
      - checkout
      - run: apt-get install -y cabal-install-head ghc-8.4.3
      - run:
          name: Update PATH at Runtime
          command: |
            echo 'export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run: ghc --version
      - run: cabal --version
      - run: cabal new-update
      - run: cabal new-build all
      - run: cabal new-test all
      - run: cabal new-run -- clash-testsuite -j16

workflows:
  version: 2
  build_multiple_ghc_version:
    jobs:
      # - build-8.2.2
      - build-8.4.3
