version: 2

aliases:
  - &env
    DEBIAN_FRONTEND: noninteractive
    CABAL_VERSION: head
  - &submodules
    run:
      name: "Checkout submodules"
      command: git submodule update --init --depth 1
  - &install_ghc
    run:
      name: Install ghc and cabal-install
      command: apt-get update -q && apt-get install -yq cabal-install-$CABAL_VERSION ghc-$GHC_VERSION
  - &update_path
    run:
      name: Update PATH
      command: |
        echo 'export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH' >> $BASH_ENV
        source $BASH_ENV
  - &cache_restore
    restore_cache:
      keys:
        - cabal-store-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "cabal.project" }}
        - cabal-store-{{ .Environment.CIRCLE_JOB }}-
  - &cache_save
    save_cache:
      key: cabal-store-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "cabal.project" }}
      paths:
        - /root/.cabal/store

  - &configure_project
    run:
      name: Disable testing with Modelsim (SystemVerilog)
      command: |
        echo -e 'package clash-testsuite\n  flags: travisci' >> cabal.project && cat cabal.project

  - &cabal-update
    run: cabal new-update

  - &build-all
    run: cabal new-build all

  - &run-tests-cabal
    run: cabal new-test all

  - &run-clash-testsuite
    run:
      name: Run clash-testsuite
      command: cabal new-run -- clash-testsuite -j16

  # When testing a pull request CircleCI,
  # fetch the result of merging it in.
  - &merge_pullrequest
    run:
      name: Checkout pull request merge result
      command: |
        if [ -n "$CIRCLE_PR_NUMBER" ]; then
          git fetch "$CIRCLE_REPOSITORY_URL" "pull/$CIRCLE_PR_NUMBER/merge:pull-$CIRCLE_PR_NUMBER-merged"
          git rev-parse "pull-$CIRCLE_PR_NUMBER-merged"
          git checkout "pull-$CIRCLE_PR_NUMBER-merged"
        fi

  - &build_default
    docker:
      - image: leonschoorl/clash-ci-image:trusty
    steps:
      - checkout
      - *merge_pullrequest
      - *submodules
      - *install_ghc
      - *update_path
      - *configure_project
      - *cache_restore
      - *cabal-update
      - *build-all
      - *run-tests-cabal
      - *cache_save
      - *run-clash-testsuite

workflows:
  version: 2
  build_and_test_clash:
    jobs:
      - ghc-8.2.2
      - ghc-8.4.3

jobs:
  ghc-8.2.2:
    environment:
      <<: *env
      GHC_VERSION: 8.2.2
    <<: *build_default
  ghc-8.4.3:
    environment:
      <<: *env
      GHC_VERSION: 8.4.3
    <<: *build_default
